name: ASP.NET Core CI

on:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Test on .NET Core for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Use .NET 2.2.108
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: dotnet build and test
      run: |
        dotnet build --configuration Debug
        dotnet test

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.108
    - name: Build with dotnet
      run: dotnet build --configuration Release
